;;; org-remoteimg-test.el --- Tests for org-remoteimg -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'org-remoteimg)

(ert-deftest org-remoteimg-registers-org-9.8-preview-handlers ()
  (when (fboundp 'org-link-preview-region)
    (should (eq (org-link-get-parameter "http" :preview)
                #'org-link-preview-http))
    (should (eq (org-link-get-parameter "https" :preview)
                #'org-link-preview-http))))

(ert-deftest org-remoteimg-computes-fractional-image-max-width ()
  (let ((org-image-max-width 0.7))
    (cl-letf (((symbol-function 'window-width)
               (lambda (&optional _window pixelwise)
                 (should pixelwise)
                 1000)))
      (should (= (org-remoteimg--image-max-width) 700)))))

(ert-deftest org-remoteimg-http-preview-passes-image-max-width ()
  (with-temp-buffer
    (org-mode)
    (insert "[[https://example.com/image.png]]")
    (goto-char (point-min))
    (let ((link (org-element-context))
          (org-image-max-width 0.7)
          image-arguments)
      (cl-letf (((symbol-function 'image-supported-file-p)
                 (lambda (_file) 'png))
                ((symbol-function 'org-remoteimg--fetch-image)
                 (lambda (&rest _arguments) "image data"))
                ((symbol-function 'org-display-inline-image--width)
                 (lambda (_link) nil))
                ((symbol-function 'org-image--align)
                 (lambda (_link) nil))
                ((symbol-function 'window-width)
                 (lambda (&optional _window _pixelwise) 1000))
                ((symbol-function 'create-image)
                 (lambda (&rest arguments)
                   (setq image-arguments arguments)
                   '(image :type png :data "image data")))
                ((symbol-function 'image-flush) #'ignore))
        (let ((overlay (make-overlay (point-min) (point-max))))
          (should (org-link-preview-http overlay nil link))
          (should (= (plist-get (nthcdr 3 image-arguments) :max-width)
                     700)))))))

(provide 'org-remoteimg-test)
;;; org-remoteimg-test.el ends here
